title: Meta Navigation Site
description: A website for simplified management and navigation of my GitHiub repositories.
theme: just-the-docs

url: https://kowalski-dawid.github.io/meta_navigation

aux_links:
  Template Repository: https://github.com/kowalski-dawid/meta_navigation

