title: Dawid Kowalski's Meta Navigation Site
description: A website for simplified management and navigation over my GitHub repositories.
theme: just-the-docs
url: https://kowalski-dawid.github.io/meta_navigation
logo: \assets\images\meta_navigation_logo.png
favicon_ico: \assets\images\meta_navigation_logo.png
search_enabled: true
search: 6
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true
  focus_shortcut_key: 'k'
heading_anchors: true
aux_links:
  Template Repository: https://github.com/kowalski-dawid/meta_navigation
nav_enabled: true
heading_anchors: true
footer_content: "Author:<a href="https://github.com/kowalski-dawid" target="_blank">Dawid Kowalski</a>"
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://kowalski-dawid.github.io/meta_navigation"
gh_edit_branch: "main"
color_scheme: dark
